firecore/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('characters', views.CharacterListView.as_view(), name='character_changelist'),
    path('characters/add/', views.CharacterCreateView.as_view(), name='character_add'),
    path('characters/<int:pk>/', views.CharacterUpdateView.as_view(), name='character_change'),
    path('characters/delete/<int:pk>', views.CharacterDeleteView.as_view(), name='character_delete'),
    path('shops', views.PlayerShopListView.as_view(), name='playershop_list'),
    path('shops/add/', views.PlayerShopCreateView.as_view(), name='playershop_add'),
    path('shops/<int:pk>/', views.PlayerShopUpdateView.as_view(), name='playershop_change'),
    path('shops/delete/<int:pk>', views.PlayerShopDeleteView.as_view(), name='playershop_delete'),
    path('ajax/load-classes/', views.load_classes, name='ajax_load_classes')
]

fireproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firecore.urls')),
    path('', include('fireshop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firecore/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


# Create your models here.
class PlayerShop(models.Model):
    shop_type_choices = [
        ("FOOD", "Tenda de Comida"),
        ("BUFF", "Buffs de Pardoner"),
        ("WEPBUFF", "Buffs para Arma"),
        ("ENCHANT", "Enchants Peito e Calça"),
        ("AWAK", "Awakening"),
        ("ROAST", "Limpa Gemas"),
        ("SEX", "Troca de Sexo"),
        ("REPLEATHER", "Repair de Leather"),
        ("REPCLOTH", "Repair de Cloth"),
        ("REPPLATE", "Repair de Plate"),
        ("REPAIR", "Repair sem Arts")
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shop_name = models.CharField(max_length=100)
    shop_type = models.CharField(max_length=100, choices=shop_type_choices)
    location = models.CharField(max_length=100)

class ClassTree(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Class(models.Model):
    class_tree = models.ForeignKey(ClassTree, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Classes"

class Character(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_gtw_char = models.BooleanField(default=True)
    is_boruta_char = models.BooleanField(default=True)
    class_tree = models.ForeignKey(ClassTree, on_delete=models.SET_NULL, null=True, related_name='+')
    first_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, related_name='+')
    second_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, related_name='+')
    third_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, related_name='+')
    build_type = models.CharField(max_length = 100, null=True, choices = [
            ("CTR", "Controle"),
            ("DPS", "Dano"),
            ("SUP", "Suporte"),
            ("TNK", "Tanque"),
        ])

    def __str__(self):
        return "{self.name}: {self.class_tree} | {self.first_class} | {self.second_class} | {self.third_class}".format(self = self)

firecore/forms.py
from django import forms
from .models import Character, Class, PlayerShop

class PlayerShopForm(forms.ModelForm):
    class Meta:
        model = PlayerShop
        widgets = {'user': forms.HiddenInput()}
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PlayerShopForm, self).__init__(*args, **kwargs)

        self.fields['user'].initial = self.user.id


class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        widgets = {'user': forms.HiddenInput()}
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(CharacterForm, self).__init__(*args, **kwargs)

        self.fields['user'].initial = self.user.id

        self.fields['first_class'].queryset = Class.objects.none()
        self.fields['second_class'].queryset = Class.objects.none()
        self.fields['third_class'].queryset = Class.objects.none()

        if 'class_tree' in self.data:
            try:
                class_tree_id = int(self.data.get('class_tree'))
                self.fields['first_class'].queryset = Class.objects.filter(class_tree_id=class_tree_id).order_by('name')
                self.fields['second_class'].queryset = Class.objects.filter(class_tree_id=class_tree_id).order_by('name')
                self.fields['third_class'].queryset = Class.objects.filter(class_tree_id=class_tree_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['first_class'].queryset = self.instance.class_tree.class_set.order_by('name')
            self.fields['second_class'].queryset = self.instance.class_tree.class_set.order_by('name')
            self.fields['third_class'].queryset = self.instance.class_tree.class_set.order_by('name')

firecore/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy
from django.shortcuts import render
from .models import Class, ClassTree, Character, PlayerShop
from .forms import CharacterForm, PlayerShopForm


# Create your views here.
class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if hasattr(self.request.user, 'shop_points'):
            context['points'] = self.request.user.shop_points.amount
        else:
            context['points'] = 0

        return context

class CharacterListView(LoginRequiredMixin, ListView):
    model = Character
    context_object_name = 'characters'

    def get_queryset(self):
        return Character.objects.filter(user_id=self.request.user.id).order_by('name')

class CharacterCreateView(LoginRequiredMixin, CreateView):
    model = Character
    form_class = CharacterForm
    success_url = reverse_lazy('character_changelist')

    def get_form_kwargs(self):
        kwargs = super(CharacterCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class CharacterUpdateView(LoginRequiredMixin, UpdateView):
    model = Character
    form_class = CharacterForm
    success_url = reverse_lazy('character_changelist')

    def get_form_kwargs(self):
        kwargs = super(CharacterUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class CharacterDeleteView(LoginRequiredMixin, DeleteView):
    model = Character
    success_url = reverse_lazy('character_changelist')

class PlayerShopListView(LoginRequiredMixin, ListView):
    model = PlayerShop
    context_object_name = 'shops'

    def get_queryset(self):
        return PlayerShop.objects.filter(user_id=self.request.user.id).order_by('shop_name')

class PlayerShopCreateView(LoginRequiredMixin, CreateView):
    model = PlayerShop
    form_class = PlayerShopForm
    success_url = reverse_lazy('playershop_list')

    def get_form_kwargs(self):
        kwargs = super(PlayerShopCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class PlayerShopUpdateView(LoginRequiredMixin, UpdateView):
    model = PlayerShop
    form_class = PlayerShopForm
    success_url = reverse_lazy('playershop_list')

    def get_form_kwargs(self):
        kwargs = super(PlayerShopUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class PlayerShopDeleteView(LoginRequiredMixin, DeleteView):
    model = PlayerShop
    success_url = reverse_lazy('playershop_list')

def load_classes(request):
    tree_id = request.GET.get('class_tree')
    classes = Class.objects.filter(class_tree_id=tree_id).order_by('name')
    return render(request, 'firecore/classes_dropdown_list_options.html', {'classes': classes})

firecore/templates/firecore/character_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Tem certeza que deseja deletar "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

firecore/templates/firecore/character_form.html
{% extends 'base.html' %}

{% block content %}
  <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

  <h2>Novo Personagem</h2>
  <hr/>

  {% if form.errors %}
    {% for error, error_field in form.errors.items%}
      <h6> Erro em {{ error_field }} </h6>
      <p>{{ error }}</p>
    {% endfor %}
  {% endif %}

  <form method="post" id="characterForm" data-classes-url="{% url 'ajax_load_classes' %}" novalidate>
    {% csrf_token %}
    <input type="hidden" name="user" value="{{form.user.initial}}" id="id_user" />
    <div class="form-group row">
      <label for="id_name" class="col-sm-2 col-form-label">Nome</label>
      <div class="col-sm-10">
        <input type="text" name="name" autofocus="" autocapitalize="none" autocomplete="name" maxlength="150" required="" id="id_name" class='form-control'
        {% if form.name.value %}
          value="{{form.name.value}}"
        {% endif %}
        >
      </div>
    </div>
    <div class="form-group row">
      <label for="id_is_gtw_char" class="col-sm-4 col-form-label">
      Usaria em GTW?</label>
      <div class="col-sm-2">
        <input type="checkbox" name="is_gtw_char" id="id_is_gtw_char"
        data-on="Sim" data-off="Não"
        {% if form.is_gtw_char.value %} checked="" {% endif %}
        data-toggle="toggle">
      </div>
      <label for="id_is_boruta_char" class="col-sm-4 col-form-label">Usaria em Boruta?</label>
      <div class="col-sm-2">
        <input type="checkbox" name="is_boruta_char" id="id_is_boruta_char"
          data-on="Sim" data-off="Não"
          {% if form.is_boruta_char.value %} checked="" {% endif %}
          data-toggle="toggle">
      </div>
    </div>
    <div class="form-group row">
      <label for="id_class_tree" class="col-sm-3 col-form-label">Profissão</label>
      <div class="col-sm-9">
        <select name="class_tree" required="" id="id_class_tree" class="form-control">
          {% for x, y in form.fields.class_tree.choices %}
            <option value="{{ x }}" {% if form.class_tree.value == x %} selected {%endif%} >
              {{y}}
            </option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label for="id_first_class" class="col-sm-3 col-form-label">Primeira Classe</label>
      <div class="col-sm-9">
        <select name="first_class" required="" id="id_first_class" class="form-control">
          {% for x, y in form.fields.first_class.choices %}
            <option value="{{ x }}" {% if form.first_class.value == x %} selected {%endif%} >
              {{y}}
            </option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label for="id_second_class" class="col-sm-3 col-form-label">Segunda Classe</label>
      <div class="col-sm-9">
        <select name="second_class" required="" id="id_second_class" class="form-control">
          {% for x, y in form.fields.second_class.choices %}
            <option value="{{ x }}" {% if form.second_class.value == x %} selected {%endif%} >
              {{y}}
            </option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label for="id_third_class" class="col-sm-3 col-form-label">Terceira Classe</label>
      <div class="col-sm-9">
        <select name="third_class" required="" id="id_third_class" class="form-control">
          {% for x, y in form.fields.third_class.choices %}
            <option value="{{ x }}" {% if form.third_class.value == x %} selected {%endif%} >
              {{y}}
            </option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label for="id_build_type" class="col-sm-3 col-form-label">Tipo de Build</label>
      <div class="col-sm-9">
        <select name="build_type" required="" id="id_build_type" class="form-control">
          {% for x, y in form.fields.build_type.choices %}
            <option value="{{ x }}" {% if form.build_type.value == x %} selected {%endif%} >
              {{y}}
            </option>
          {% endfor %}
        </select>
      </div>
    </div>
    <button class="btn btn-primary" type="submit">Salvar</button>
    <a class="btn btn-secondary" href="{% url 'character_changelist' %}">Voltar</a>
  </form>
  <script>
    $("#id_class_tree").change(function () {
      var url = $("#characterForm").attr("data-classes-url");
      var classTreeId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'class_tree': classTreeId
        },
        success: function (data) {
          $("#id_first_class").html(data);
          $("#id_second_class").html(data);
          $("#id_third_class").html(data);
        }
      });

    });
  </script>

{% endblock %}

firecore/templates/firecore/character_list.html
{% extends 'base.html' %}

{% block title %}Fire Command Center{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <h2>Lista de Personagens de {{ user.username }}</h2>
  {% endif %}

  <p>
    <a href="{% url 'character_add' %}">Novo Personagem</a>
  </p>
      <div class="row">
        {% for character in characters %}
          <div class="col-sm-4">
            <div class="card">
              <div class="card-header">
                <h6>{{ character.name }}</h6>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ character.first_class }}</li>
                <li class="list-group-item">{{ character.second_class }}</li>
                <li class="list-group-item">{{ character.third_class }}</li>
              </ul>
              <div class="card-body">
                <a href="{% url 'character_change' character.pk %}" class="card-link">Editar</a>
                <a href="{% url 'character_delete' character.pk %}" class="card-link">Remover</a>
              </div>
            </div>
          </div>
        {% empty %}
          <tr>
            <td colspan="5">Nenhum personagem encontrado. <a href="{% url 'character_add' %}">Adicione o primeiro</a>.</td>
          </tr>
        {% endfor %}
      </div>

{% endblock %}

firecore/templates/firecore/classes_dropdown_list_options.html
<option value="">---------</option>
{% for clss in classes %}
	<option value="{{ clss.pk }}">{{ clss.name }}</option>
{% endfor %}

firecore/templates/firecore/dashboard.html
{% extends 'base.html' %}

{% block title %}Fire Command Center{% endblock %}

{% block content %}



{% endblock %}

firecore/templates/firecore/playershop_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Tem certeza que deseja deletar "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

firecore/templates/firecore/playershop_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Nova Loja</h2>

  <form method="post" id="playerShopForm" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button class="btn btn-primary" type="submit">Salvar</button>
    <a class="btn btn-secondary" href="{% url 'playershop_list' %}">Voltar</a>
  </form>
{% endblock %}

firecore/templates/firecore/playershop_list.html
{% extends 'base.html' %}

{% block title %}Fire Command Center{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <h2>Lista de Lojas de {{ user.username }}</h2>
  {% endif %}

  <p>
    <a href="{% url 'playershop_add' %}">Nova Loja</a>
  </p>
      <div class="row">
        {% for shop in shops %}
          <div class="col-sm-4">
            <div class="card">
              <div class="card-header">
                <h6>{{ shop.shop_name }}</h6>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Dono/a: {{ shop.user.username }}</li>
                <li class="list-group-item">Tipo: {{ shop.shop_type }}</li>
                <li class="list-group-item">Local: {{ shop.location }}</li>
              </ul>
              <div class="card-body">
                <a href="{% url 'playershop_change' shop.pk %}" class="card-link">Editar</a>
                <a href="{% url 'playershop_delete' shop.pk %}" class="card-link">Remover</a>
              </div>
            </div>
          </div>
        {% empty %}
          <tr>
            <td colspan="5">Nenhum personagem encontrado. <a href="{% url 'playershop_add' %}">Adicione o primeiro</a>.</td>
          </tr>
        {% endfor %}
      </div>

{% endblock %}