firecore/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('characters', views.CharacterListView.as_view(), name='character_changelist'),
    path('characters/add/', views.CharacterCreateView.as_view(), name='character_add'),
    path('characters/<int:pk>/', views.CharacterUpdateView.as_view(), name='character_change'),
    path('characters/delete/<int:pk>', views.CharacterDeleteView.as_view(), name='character_delete'),
    path('shops', views.PlayerShopListView.as_view(), name='playershop_list'),
    path('shops/add/', views.PlayerShopCreateView.as_view(), name='playershop_add'),
    path('shops/<int:pk>/', views.PlayerShopUpdateView.as_view(), name='playershop_change'),
    path('shops/delete/<int:pk>', views.PlayerShopDeleteView.as_view(), name='playershop_delete'),
    path('ajax/load-classes/', views.load_classes, name='ajax_load_classes')
]

fireproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firecore.urls')),
    path('', include('fireshop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fireshop/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from firecore.models import Character
from django.db.models import F
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateTimeField(default=timezone.now)
    has_party_planning = models.BooleanField(default=True)

    def __str__(self):
        return "{} {}".format(self.name,
                              self.date.date().strftime("%d/%m/%Y"))

    def get_going_attendances(self):
        return self.attendances.filter(attendance_type='going')

    def get_maybe_attendances(self):
        return self.attendances.filter(attendance_type='maybe')

    def get_not_going_attendances(self):
        return self.attendances.filter(attendance_type='notgoing')


class AttendanceTypes(models.TextChoices):
    GOING =  'going', _("Vou"),
    MAYBE =  'maybe', _("Talvez"),
    NOTGOING =  'notgoing', _("Não Vou"),

class EventAttendance(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_attendances')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='attendances')
    attendance_type = models.CharField(max_length=100, choices=AttendanceTypes.choices)
    creation_date = models.DateTimeField(auto_now_add=True)
    confirmation_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return "{}: {}".format(self.user.username, AttendanceTypes[self.attendance_type.upper()].label)

    def get_attendance_type_label(self):
        return AttendanceTypes[self.attendance_type.upper()].label

class EventAttendanceCategory(models.Model):
    name = models.CharField(max_length=100)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='attendance_categories')
    points_amount = models.IntegerField()

    def __str__(self):
        return "{}: {}".format(self.event.name, self.name)

    class Meta:
        verbose_name_plural = "Event Attendance Categories"

class EventAttendanceConfirmation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="attendance_confirmations")
    confirmation_date = models.DateTimeField(auto_now_add=True)
    attendance_category = models.ForeignKey(EventAttendanceCategory,
                                            on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.generate_user_points()

    def generate_user_points(self):
        point_history_entry = PlayerPointsHistory(user=self.user,
                              amount_points= self.attendance_category.points_amount)
        point_history_entry.description = "{}".format(self.attendance_category)
        point_history_entry.save()

    def __str__(self):
        return "{}: {} em {}".format(self.user, self.attendance_category.name, self.event)


class PlayerPoints(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                primary_key=True,
                                related_name='shop_points')
    amount = models.IntegerField()
    last_updated_date = models.DateTimeField(auto_now=True)

    def add(self, value):
        self.amount = F('amount') + value
        self.save()

    def __str__(self):
        return "{}: {} ponto(s).".format(self.user.username, self.amount)

class PlayerPointsHistory(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    amount_points = models.IntegerField()
    total_points_on_date = models.IntegerField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if hasattr(self.user, 'shop_points'):
            self.total_points_on_date = self.user.shop_points.amount + self.amount_points
        else:
            self.total_points_on_date = self.amount_points
        super().save(*args, **kwargs)
        self.update_user_points()

    def update_user_points(self):
        try:
            if hasattr(self.user, 'shop_points'):
                self.user.shop_points.add(self.amount_points)
            else:
                shop_points = PlayerPoints(user=self.user, amount=self.amount_points)
                shop_points.save()
        except:
            self.delete()

    def __str__(self):
        return "{}: {}".format(self.user.username, self.description)

class ShopItem(models.Model):
    SHOP_ITEM_IMAGE_FOLDER = 'shop_items/'

    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to=SHOP_ITEM_IMAGE_FOLDER)
    points_cost = models.IntegerField()

    def __str__(self):
        return self.name

class ShopItemRedeem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shop_item = models.ForeignKey(ShopItem, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    additional_notes = models.CharField(max_length=100)

    def confirm(self):
        user_points = user.player_points

class EventParty(models.Model):
    event =  models.ForeignKey(Event, on_delete=models.CASCADE)
    party_number = models.IntegerField()
    first_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')
    second_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')
    third_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')
    fourth_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')
    fifth_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')

templates/base.html
{% load static %}

<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Fire Command Center{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/9490310c29.js" crossorigin="anonymous"></script>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">
              <img src="{% static 'img/firelogo.png' %}" width="30" height="30" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if user.is_authenticated %}
              <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard' %}">Inicio</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarAccount" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Minha Conta
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarAccount">
                          <a class="dropdown-item" href="{% url 'character_changelist' %}">Personagens</a>
                          <a class="dropdown-item" href="{% url 'playershop_list' %}">Lojas</a>
                        </div>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarAccount" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Loja Fire
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarAccount">
                          <a class="dropdown-item" href="{% url 'shop_item_list' %}">Ver Loja</a>
                          <a class="dropdown-item" href="{% url 'player_points_history_list' %}">Histórico de Pontos</a>
                          <a class="dropdown-item" href="#">Histórico de Resgates</a>
                        </div>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{%url 'event_list' %}">Eventos</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="https://fireemblemguild.forumeiros.com/" target="about:blank">Fórum</a>
                      </li>
                      {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="/admin">Admin</a>
                        </li>
                      {% endif %}
                  </ul>
                  <ul class='nav navbar-nav ml-auto'>
                    <li class="nav-item">
                      <a class="nav-link" href="{%url 'logout' %}">Sair</a>
                    </li>
                  </ul>
              </div>
            {% else %}
              <div class="collapse navbar-collapse" id="navbarNav">
                  <span class="navbar-text">
                    Fire Emblem Comm Center v0.1
                  </span>
                  <ul class="navbar-nav ml-auto">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard' %}">Login</a>
                      </li>
                  </ul>
              </div>
            {% endif %}
    </nav>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <div class="container" style="padding-top:50px">

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{message.level_tag}} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Fire Command Center{% endblock %}

{% block content %}

<h1>Bem-vindo, {{user.username}}!</h1>
<h5>Você possui {{ points }} pontos na loja. <a href="{% url 'shop_item_list' %}"> Use-os aqui!</a></h5>

<a href="{% url 'character_changelist' %}"> Meus personagens</a>
{% endblock %}