firecore/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('characters', views.CharacterListView.as_view(), name='character_changelist'),
    path('characters/add/', views.CharacterCreateView.as_view(), name='character_add'),
    path('characters/<int:pk>/', views.CharacterUpdateView.as_view(), name='character_change'),
    path('characters/delete/<int:pk>', views.CharacterDeleteView.as_view(), name='character_delete'),
    path('shops', views.PlayerShopListView.as_view(), name='playershop_list'),
    path('shops/add/', views.PlayerShopCreateView.as_view(), name='playershop_add'),
    path('shops/<int:pk>/', views.PlayerShopUpdateView.as_view(), name='playershop_change'),
    path('shops/delete/<int:pk>', views.PlayerShopDeleteView.as_view(), name='playershop_delete'),
    path('ajax/load-classes/', views.load_classes, name='ajax_load_classes')
]

fireproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firecore.urls')),
    path('', include('fireshop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fireshop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('events/', views.EventListView.as_view(), name='event_list'),
    path('events/new', views.EventCreateView.as_view(), name='event_add'),
    path('events/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
    path('events/<int:pk>/update', views.EventUpdateView.as_view(), name='event_update'),
    path('events/<int:pk>/attendance', views.EventAttendanceListView.as_view(), name='event_attendance_list'),
    path('events/<int:eid>/attendance/add', views.EventAttendanceCategoryCreateView.as_view(),
        name='event_attendance_category_add'),
    path('events/<int:eid>/categories/', views.EventAttendanceCategoryListView.as_view(),
        name='event_attendance_category_update'),
    path('events/<int:eid>/attendance/<int:pk>/edit', views.EventAttendanceCategoryUpdateView.as_view(),
        name='event_attendance_category_update'),
    path('events/<int:event>/attendance/confirm',
        views.EventAttendanceConfirmationView.as_view(), name='event_attendance_confirm'),
    path('events/<int:pk>/attendance/<str:typ>', views.EventAttendanceCreateView.as_view(), name='event_attendance_add'),
    path('events/<int:pk>/planner/', views.PartyPlanningView.as_view(), name='party_planner'),
    path('shop/', views.ShopListView.as_view(), name='shop_item_list'),
    path('shop/points/new', views.PlayerPointsCreateView.as_view(), name='player_points_create'),
    path('shop/points/history', views.PlayerPointsHistoryListView.as_view(), name='player_points_history_list'),
    path('shop/<int:pk>/redeem', views.ShopItemRedeemView.as_view(), name='shop_item_redeem'),
    path('shop/items/new', views.ShopItemCreateView.as_view(), name='shop_item_create'),
    path('shop/items/<int:pk>', views.ShopItemUpdateView.as_view(), name='shop_item_update'),
]

firecore/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


# Create your models here.
class PlayerShop(models.Model):
    shop_type_choices = [
        ("FOOD", "Tenda de Comida"),
        ("BUFF", "Buffs de Pardoner"),
        ("WEPBUFF", "Buffs para Arma"),
        ("ENCHANT", "Enchants Peito e Calça"),
        ("AWAK", "Awakening"),
        ("ROAST", "Limpa Gemas"),
        ("SEX", "Troca de Sexo"),
        ("REPLEATHER", "Repair de Leather"),
        ("REPCLOTH", "Repair de Cloth"),
        ("REPPLATE", "Repair de Plate"),
        ("REPAIR", "Repair sem Arts")
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shop_name = models.CharField(max_length=100)
    shop_type = models.CharField(max_length=100, choices=shop_type_choices)
    location = models.CharField(max_length=100)

class ClassTree(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Class(models.Model):
    class_tree = models.ForeignKey(ClassTree, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Classes"

class Character(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_gtw_char = models.BooleanField(default=True)
    is_boruta_char = models.BooleanField(default=True)
    class_tree = models.ForeignKey(ClassTree, on_delete=models.SET_NULL, null=True, related_name='+')
    first_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, related_name='+')
    second_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, related_name='+')
    third_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, related_name='+')
    build_type = models.CharField(max_length = 100, null=True, choices = [
            ("CTR", "Controle"),
            ("DPS", "Dano"),
            ("SUP", "Suporte"),
            ("TNK", "Tanque"),
        ])

    def __str__(self):
        return "{self.name}: {self.class_tree} | {self.first_class} | {self.second_class} | {self.third_class}".format(self = self)

fireshop/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from firecore.models import Character
from django.db.models import F
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateTimeField(default=timezone.now)
    has_party_planning = models.BooleanField(default=True)

    def __str__(self):
        return "{} {}".format(self.name,
                              self.date.date().strftime("%d/%m/%Y"))

    def get_going_attendances(self):
        return self.attendances.filter(attendance_type='going')

    def get_maybe_attendances(self):
        return self.attendances.filter(attendance_type='maybe')

    def get_not_going_attendances(self):
        return self.attendances.filter(attendance_type='notgoing')


class AttendanceTypes(models.TextChoices):
    GOING =  'going', _("Vou"),
    MAYBE =  'maybe', _("Talvez"),
    NOTGOING =  'notgoing', _("Não Vou"),

class EventAttendance(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_attendances')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='attendances')
    attendance_type = models.CharField(max_length=100, choices=AttendanceTypes.choices)
    creation_date = models.DateTimeField(auto_now_add=True)
    confirmation_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return "{}: {}".format(self.user.username, AttendanceTypes[self.attendance_type.upper()].label)

    def get_attendance_type_label(self):
        return AttendanceTypes[self.attendance_type.upper()].label

class EventAttendanceCategory(models.Model):
    name = models.CharField(max_length=100)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='attendance_categories')
    points_amount = models.IntegerField()

    def __str__(self):
        return "{}: {}".format(self.event.name, self.name)

    class Meta:
        verbose_name_plural = "Event Attendance Categories"

class EventAttendanceConfirmation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="attendance_confirmations")
    confirmation_date = models.DateTimeField(auto_now_add=True)
    attendance_category = models.ForeignKey(EventAttendanceCategory,
                                            on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.generate_user_points()

    def generate_user_points(self):
        point_history_entry = PlayerPointsHistory(user=self.user,
                              amount_points= self.attendance_category.points_amount)
        point_history_entry.description = "{}".format(self.attendance_category)
        point_history_entry.save()

    def __str__(self):
        return "{}: {} em {}".format(self.user, self.attendance_category.name, self.event)


class PlayerPoints(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                primary_key=True,
                                related_name='shop_points')
    amount = models.IntegerField()
    last_updated_date = models.DateTimeField(auto_now=True)

    def add(self, value):
        self.amount = F('amount') + value
        self.save()

    def __str__(self):
        return "{}: {} ponto(s).".format(self.user.username, self.amount)

class PlayerPointsHistory(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    amount_points = models.IntegerField()
    total_points_on_date = models.IntegerField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if hasattr(self.user, 'shop_points'):
            self.total_points_on_date = self.user.shop_points.amount + self.amount_points
        else:
            self.total_points_on_date = self.amount_points
        super().save(*args, **kwargs)
        self.update_user_points()

    def update_user_points(self):
        try:
            if hasattr(self.user, 'shop_points'):
                self.user.shop_points.add(self.amount_points)
            else:
                shop_points = PlayerPoints(user=self.user, amount=self.amount_points)
                shop_points.save()
        except:
            self.delete()

    def __str__(self):
        return "{}: {}".format(self.user.username, self.description)

class ShopItem(models.Model):
    SHOP_ITEM_IMAGE_FOLDER = 'shop_items/'

    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to=SHOP_ITEM_IMAGE_FOLDER)
    points_cost = models.IntegerField()

    def __str__(self):
        return self.name

class ShopItemRedeem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shop_item = models.ForeignKey(ShopItem, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    additional_notes = models.CharField(max_length=100)

    def confirm(self):
        user_points = user.player_points

class EventParty(models.Model):
    event =  models.ForeignKey(Event, on_delete=models.CASCADE)
    party_number = models.IntegerField()
    first_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')
    second_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')
    third_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')
    fourth_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')
    fifth_character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, related_name='+')

fireshop/forms.py
from django import forms
from .models import Event
from tempus_dominus.widgets import DateTimePicker

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'date', 'has_party_planning']
        widgets = {'date': DateTimePicker(options={
            'format': 'D/M/YYYY H:mm:ss'
            })}

fireshop/templates/fireshop/event_attendance_category_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Nova Categoria de Presença</h2>
  <hr/>

  {% if form.errors %}
    {% for error, error_field in form.errors.items%}
      <h6> Erro em {{ error_field }} </h6>
      <p>{{ error }}</p>
    {% endfor %}
  {% endif %}

  <form method="post" id="characterForm" data-classes-url="{% url 'ajax_load_classes' %}" novalidate>
    {% csrf_token %}
    <input type="hidden" name="event" value="{{event.pk}}" id="id_event" />
    <div class="form-group row">
      <label for="id_name" class="col-sm-2 col-form-label">Nome</label>
      <div class="col-sm-4">
        <input type="text" name="name" autofocus="" autocapitalize="none" autocomplete="name" maxlength="150" required="" id="id_name" class='form-control'
        {% if form.name.value %}
          value="{{form.name.value}}"
        {% endif %}
        >
      </div>
    </div>
    <div class="form-group row">
      <label for="id_name" class="col-sm-2 col-form-label">Pontos</label>
      <div class="col-sm-4">
        <input type="number" name="points_amount" autofocus="" autocapitalize="none" autocomplete="points_amount" maxlength="150" required="" id="id_points_amount" class='form-control'
        {% if form.points_amount.value %}
          value="{{form.points_amount.value}}"
        {% endif %}
        >
      </div>
    </div>
    <button class="btn btn-primary" type="submit">Salvar</button>
    <a class="btn btn-secondary" href="{% url 'event_detail' event.pk %}">Voltar</a>
  </form>
{% endblock %}

fireshop/templates/fireshop/event_attendance_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
  <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

  <h2>Lista de Presença para {{event}}</h2>
  <hr/>
    <div class="form-group row">
      <span class="col-sm-2">Nome:</span>
      <div class="col-sm-4">
        {{event.name}}
      </div>
    </div>
    <div class="form-group row">
      <span for="id_description" class="col-sm-2">Data do Evento:</span>
      <div class="col-sm-4">
        {{ event.date }}
      </div>
    </div>

     <table class="table table-hover table-dark">
        <thead>
          <th colspan='2' scope="col">
            Membro
          </th>
          {% for category in attendance_categories %}
            <th scope="col">
              {{ category.name}}
            </th>
          {% endfor %}
        </thead>
        <tbody>
          {% if confirmed %}
            {% for confirmation in confirmed %}
              {% if forloop.first %}
                <tr scope="row">
                  <td colspan="{{colspan}}" class='text-center'> Presenças já confirmadas
                </tr>
              {% endif %}
            <tr scope="row" class="member-data">
              <td colspan='2' data-user-id="{{confirmation.user.id}}">{{ confirmation.user.username }}</td>
                {% for category in attendance_categories %}
                  <td>
                    <input type="radio" name="attendance_user_{{confirmation.user.id}}" class="attendance-category"
              value="{{ category.id }}" id="attendance_user_{{confirmation.user.id}}"
              {% if confirmation.attendance_category.id == category.id %} checked {% else %} disabled {% endif %}
              />
                  </td>
                {% endfor %}
            </tr>
            {% endfor %}
          {% else %}
          {% for member in going %}
            {% if forloop.first %}
              <tr scope="row">
                <td colspan="{{colspan}}" class='text-center'> Membros que responderam "Vou"
              </tr>
            {% endif %}
          <tr scope="row" class="member-data">
            <td colspan='2' data-user-id="{{member.user.id}}">{{ member.user.username }}</td>
              {% for category in attendance_categories %}
                <td>
                  <input type="radio" name="attendance_user_{{member.user.id}}" class="attendance-category"
            value="{{ category.id }}" id="attendance_user_{{member.user.id}}"/>
                </td>
              {% endfor %}
          </tr>
          {% endfor %}
          {% for member in maybe %}
            {% if forloop.first %}
              <tr scope="row">
                <td colspan="{{colspan}}" class='text-center'> Membros que responderam "Talvez"
              </tr>
            {% endif %}
            <tr scope="row" class="member-data">
              <td colspan='2' data-user-id="{{member.user.id}}">{{ member.user.username }}</td>
                {% for category in attendance_categories %}
                  <td>
                    <input type="radio" name="attendance_user_{{member.user.id}}" class="attendance-category"
              value="{{ category.id }}" id="attendance_user_{{member.user.id}}"/>
                  </td>
                {% endfor %}
            </tr>
          {% endfor %}
          {% for member in notgoing %}
            {% if forloop.first %}
              <tr scope="row">
                <td colspan="{{colspan}}" class='text-center'> Membros que responderam "Não Vou"
              </tr>
            {% endif %}
            <tr scope="row" class="member-data">
              <td colspan='2' data-user-id="{{member.user.id}}">{{ member.user.username }}</td>
                {% for category in attendance_categories %}
                  <td class="attendance-categories">
                    <input type="radio" name="attendance_user_{{member.user.id}}" class="attendance-category"
              value="{{ category.id }}" id="attendance_user_{{member.user.id}}"/>
                  </td>
                {% endfor %}
            </tr>
          {% endfor %}
          {% for member in unanswered %}
            {% if forloop.first %}
              <tr scope="row">
                <td colspan="{{colspan}}" class='text-center'> Membros que não responderam
              </tr>
            {% endif %}
            <tr scope="row" class="member-data">
              <td colspan='2' data-user-id="{{member.id}}">{{ member.username }}</td>
                {% for category in attendance_categories %}
                  <td>
                    <input type="radio" name="attendance_user_{{member.id}}" class="attendance-category"
              value="{{ category.id }}" id="attendance_user_{{member.id}}"/>
                  </td>
                {% endfor %}
            </tr>
          {% endfor %}
          {% endif %}
        </tbody>
      </table>
    <a class="btn btn-primary" href="{% url 'event_detail' event.pk %}" type="submit">Voltar</a>
    <form method="post" action="{% url 'event_attendance_confirm' event.pk %}" id="attendancesForm" data-classes-url="{% url 'ajax_load_classes' %}" novalidate>
      {% csrf_token %}
      <input type="hidden" name="attendances" id="attendanceList" value=""/>
      <button class="btn btn-primary" id="submitAttendances" type="submit">Confirmar</button>
    </form>

    <script src="{% static 'js/attendance.js' %}"></script>
{% endblock %}

fireshop/templates/fireshop/event_form.html
{% extends 'base.html' %}

{% block content %}
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
  <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

  <h2>Novo Evento</h2>
  <hr/>

  {% if form.errors %}
    {% for error, error_field in form.errors.items%}
      <h6> Erro em {{ error_field }} </h6>
      <p>{{ error }}</p>
    {% endfor %}
  {% endif %}

  <form method="post" id="eventForm" novalidate>
    {% csrf_token %}
    <div class="form-group row">
      <label for="id_name" class="col-sm-2 col-form-label">Nome:</label>
      <div class="col-sm-4">
        <input type="text" name="name" autofocus="" autocapitalize="none" autocomplete="name" maxlength="150" required="" id="id_name" class='form-control'
        {% if form.name.value %}
          value="{{form.name.value}}"
        {% endif %}
        >
      </div>
    </div>
    <div class="form-group row">
      <label for="id_description" class="col-sm-2 col-form-label">Data do Evento:</label>
      <div class="col-sm-4">
        {{ form.date }}
      </div>
    </div>
    <div class="form-group row">
      <label for="id_has_party_planning" class="col-sm-4 col-form-label">
      Gostaria de planejar PTs para esse evento?</label>
      <div class="col-sm-2">
        <input type="checkbox" name="has_party_planning" id="id_has_party_planning"
        data-on="Sim" data-off="Não"
        {% if form.has_party_planning.value %} checked="" {% endif %}
        data-toggle="toggle">
      </div>
    </div>
    <button class="btn btn-primary" type="submit">Salvar</button>
    <a class="btn btn-secondary" href="{% url 'event_list' %}">Voltar</a>
  </form>

{% endblock %}

fireshop/templates/fireshop/event_list.html
{% extends 'base.html' %}
{% load tz %}

{% block title %}Fire Command Center{% endblock %}

{% block content %}
  <h2>Eventos depois de {{ now }}</h2>
  <p>
    {% if user.is_staff %}
      <a class="btn btn-primary" href="{% url 'event_add' %}">Novo Evento</a>
    {% endif %}
      <a class="btn btn-primary" href="{% url 'event_list' %}?show_all=true">Mostrar Todos</a>
  </p>
      <div class="row">
        {% for event in events %}
          <div class="col-sm-4">
            <div class="card">
              <div class="card-header">
                {% if user.is_staff %}
                  <h6><a href="{% url 'event_detail' event.pk %}">{{ event.name }}</a></h6>
                {% else %}
                  <h6>{{ event.name }}</h6>
                {% endif %}
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ event.date|date:'l, j \d\e F \d\e o' }} {{event.date|time}}</li>
              </ul>
              <div class="card-body">
                <a {% if event in user_going %} class='font-weight-bold' {% endif %} href="{% url 'event_attendance_add' event.pk 'going' %}" class="card-link">Vou</a>
                <span class="badge badge-primary badge-pill">{{ event.get_going_attendances|length }}</span>
                <a {% if event in user_maybe %} class='font-weight-bold' {% endif %} href="{% url 'event_attendance_add' event.pk 'maybe'  %}" class="card-link">Talvez</a>
                <span class="badge badge-primary badge-pill">{{ event.get_maybe_attendances|length }}</span>
                <a {% if event in user_not_going %} class='font-weight-bold' {% endif %} href="{% url 'event_attendance_add' event.pk 'notgoing'  %}" class="card-link">Não Vou</a>
                <span class="badge badge-primary badge-pill">{{ event.get_not_going_attendances|length }}</span>
                {% if event.has_party_planning and user.is_staff %}
                	<a href="{% url 'event_list' %}" class="card-link">Planejar PTs</a>
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

{% endblock %}

fireshop/templates/fireshop/playerpoints_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Novo registro de pontos para membro</h2>
  <hr/>

  {% if form.errors %}
    {% for error, error_field in form.errors.items%}
      <h6> Erro em {{ error_field }} </h6>
      <p>{{ error }}</p>
    {% endfor %}
  {% endif %}

  <form method="post" id="playerPointsForm" novalidate>
    {% csrf_token %}
    <div class="form-group row">
      <label for="id_name" class="col-sm-2 col-form-label">Nome</label>
      <div class="col-sm-4">
        <select name="user" required="" id="id_user" class="form-control">
          {% for x, y in form.fields.user.choices %}
            <option value="{{ x }}" {% if form.user.value == x %} selected {%endif%} >
              {{y}}
            </option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label for="id_name" class="col-sm-2 col-form-label">Pontos</label>
      <div class="col-sm-4">
        <input type="number" name="amount" autofocus="" autocapitalize="none" autocomplete="amount" maxlength="150" required="" id="id_amount" class='form-control'
        {% if form.amount.value %}
          value="{{form.amount.value}}"
        {% endif %}
        >
      </div>
    </div>
    <button class="btn btn-primary" type="submit">Salvar</button>
    <a class="btn btn-secondary" href="{% url 'shop_item_list' %}">Voltar</a>
  </form>
{% endblock %}

fireshop/templates/fireshop/shopitem_form.html
{% extends 'base.html' %}

{% block content %}
  <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
  <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

  <h2>Novo Item de Loja</h2>
  <hr/>

  {% if form.errors %}
    {% for error, error_field in form.errors.items%}
      <h6> Erro em {{ error_field }} </h6>
      <p>{{ error }}</p>
    {% endfor %}
  {% endif %}

  <form method="post" id="shopItemForm" novalidate enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="form-group row">
      <label for="id_name" class="col-sm-2 col-form-label">Nome</label>
      <div class="col-sm-10">
        <input type="text" name="name" autofocus="" autocapitalize="none" autocomplete="name" maxlength="150" required="" id="id_name" class='form-control'
        {% if form.name.value %}
          value="{{form.name.value}}"
        {% endif %}
        >
      </div>
    </div>
    <div class="form-group row">
      <label for="id_description" class="col-sm-2 col-form-label">Descrição</label>
      <div class="col-sm-10">
        <input type="text" name="description" autofocus="" autocapitalize="none" autocomplete="description" maxlength="150" required="" id="id_description" class='form-control'
        {% if form.description.value %}
          value="{{form.description.value}}"
        {% endif %}
        >
      </div>
    </div>
    <div class="form-group row">
      <label for="id_image" class="col-sm-2 col-form-label">Imagem</label>
      <div class="col-sm-10">
        {% if form.image.value %}
          Atual: <a href="/media/{{ form.image.value }}">{{ form.image.value }}</a>
        {% endif %}
        <input type="file" name="image" accept="image/*" required="" id="id_image"/>
      </div>
    </div>
    <div class="form-group row">
      <label for="id_points_ammount" class="col-sm-2 col-form-label">Pontos necessários</label>
      <div class="col-sm-10">
        <input type="number" name="points_ammount" id="id_points_ammount"
        {% if form.points_ammount.value %}
          value="{{form.points_ammount.value}}"
        {% endif %}
        >
      </div>
    </div>
    <button class="btn btn-primary" type="submit">Salvar</button>
    <a class="btn btn-secondary" href="{% url 'shop_item_list' %}">Voltar</a>
  </form>

{% endblock %}